%% Create CruiseControlMode MCDC Test File
% Tests for MCDC 100%% coverage of crs_controller/CruiseControlMode
% Generated by MATLAB script

% --- Setup ---
testFilePath = 'C:\work\demos\CruiseControlFromModel\tests\CruiseControlMode_MCDC_Tests.mldatx';
inputsDir = 'C:\work\demos\CruiseControlFromModel\tests\test_inputs_ccm';
if ~isfolder(inputsDir), mkdir(inputsDir); end
if isfile(testFilePath)
    sltest.testmanager.clear();
    delete(testFilePath);
end

Ts = 0.01; % sample time (s)